---
language: node_js
node_js:
  - "6"

sudo: false

cache:
  directories:
    - $HOME/.npm

before_install:
  - npm config set spin false
  - npm install -g phantomjs-prebuilt
  - npm install -g codecov
  - phantomjs --version

install:
  - npm install

script:
  - npm test
  - codecov # push coverage report to codecov

branches:
  only:
  - master
  - development

env:
  - COVERAGE=true # generate coverage report with ember-cli-code-coverage
